apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ${EKS_CLUSTER_NAME}
  region: ${AWS_REGION}
  version: "${EKS_VERSION}"

managedNodeGroups:
  - name: ${EKS_CLUSTER_NAME}-ng
    instanceType: ${EKS_NODE_INSTANCE_TYPE}
    desiredCapacity: ${EKS_NODE_DESIRED_CAPACITY}
    minSize: ${EKS_NODE_MIN_SIZE}
    maxSize: ${EKS_NODE_MAX_SIZE}
    volumeSize: ${EKS_NODE_VOLUME_SIZE}
    labels:
      workload: store-platform
